[project]
name = "bitcoin-blockchain"
version = "0.1.0"
description = "Implementação de uma Criptomoeda Distribuída Simplificada (Bitcoin-like)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
blockchain-node = "src.blockchain:main"
